services:
  frontend_dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
      - NODE_ENV=DEVELOPMENT
    volumes:
      - ./src:/app/src
  