services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  backend_dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=DEVELOPMENT
      - DB_HOST=raketnow-2354.postgresql.b.osc-fr1.scalingo-dbs.com
      - DB_PORT=34815
      - DB_USER=raketnow_2354
      - DB_PASSWORD=9dRbRHT64HJWnzWDecHrStXxwf0QC1BL3lcpmUzEdUIS3WE32udVyl5iTrY1_Vmb
      - DB_DATABASE=raketnow_2354
      - DB_SSL=true
    volumes:
      - ./src:/app/src
  
volumes:
  minio_data: